name: n8n_shortlink_compose
services:
  n8n-shortlink:
    image: ghcr.io/ivov/n8n-shortlink:latest
    container_name: n8n-shortlink
    profiles: ["production"]
    ports:
      - 3001:3001
    env_file:
      - .env.production # only for N8N_SHORTLINK_SENTRY_DSN
    environment:
      - N8N_SHORTLINK_HOST=0.0.0.0
      - N8N_SHORTLINK_ENVIRONMENT=production
    volumes:
      - ${HOME}/.n8n-shortlink:/root/.n8n-shortlink
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - n8n-shortlink-network

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    profiles: ["production"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=21600 # every 6 hours
    restart: unless-stopped
    networks:
      - n8n-shortlink-network

  n8n-shortlink-local:
    image: n8n-shortlink:local
    container_name: n8n-shortlink
    profiles: ["local"]
    ports:
      - 3001:3001
    environment:
      - N8N_SHORTLINK_HOST=0.0.0.0
      - N8N_SHORTLINK_ENVIRONMENT=development
    volumes:
      - ${HOME}/.n8n-shortlink:/root/.n8n-shortlink
    restart: unless-stopped
    networks:
      - n8n-shortlink-network

networks:
  n8n-shortlink-network:
    name: n8n-shortlink-network
    external: true

