linters:
  enable:
    - govet        # correctness
    - errcheck     # error handling
    - staticcheck  # static analysis
    - gosec        # security
    - revive       # best practices

linters-settings:
  gosec:
    excludes:
      - G104  # disregard errors not requiring explicit handling
      - G204  # allow subprocess launching with validated config inputs

run:
  timeout: 5m
  tests: true