server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: n8n-shortlink
    static_configs:
    - targets:
        - localhost
      labels:
        job: n8n-shortlink
        __path__: /home/ivov/.n8n-shortlink/n8n-shortlink.log

  - job_name: n8n-shortlink-backups
    static_configs:
      - targets:
          - localhost
        labels:
          job: n8n-shortlink-backups
          __path__: /home/ivov/deploy/backups.log