version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - n8n-shortlink-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config-prometheus.yml:/etc/prometheus/config-prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/config-prometheus.yml
    networks:
      - n8n-shortlink-network

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    user: root
    security_opt:
      - no-new-privileges:true
    networks:
      - n8n-shortlink-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 9092:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true
    networks:
      - n8n-shortlink-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ./config-loki.yml:/etc/loki/local-config.yml
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - n8n-shortlink-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./config-promtail.yml:/etc/promtail/config.yml
      - ${HOME}/.n8n-shortlink:/n8n-shortlink/data
      - ${HOME}/deploy:/deploy
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - n8n-shortlink-network

volumes:
  grafana_data:
  prometheus_data:

networks:
  n8n-shortlink-network:
    name: n8n-shortlink-network
    external: true
