---
- name: Set up app dir (~/.n8n-shortlink)
  hosts: all
  vars:
    app_dir: "{{ ansible_user_dir }}/.n8n-shortlink"
    app_db: "{{ app_dir }}/n8n-shortlink.sqlite"

  tasks:
    - name: Create app dir
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0700"

    - name: Remember app dir
      set_fact:
        app_dir: "{{ app_dir }}" 

    - name: Create empty SQLite database
      shell: "sqlite3 {{ app_db }} ''"
      args:
        creates: "{{ app_db }}" # run `shell` _if and only if_ this file does not yet exist
