---
- name: Set up app dir (~/.n8n-shortlink)
  hosts: all
  vars:
    app_dir: "{{ ansible_user_dir }}/.n8n-shortlink"
    app_db: "{{ app_dir }}/n8n-shortlink.sqlite"
  vars_prompt:
    - name: sentry_dsn
      prompt: Enter Sentry DSN
      private: no

  tasks:
    - name: Create app dir
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: "0700"

    - name: Create empty SQLite database
      shell: "sqlite3 {{ app_db }} ''"
      args:
        creates: "{{ app_db }}" # run `shell` _if and only if_ this file does not yet exist

    - name: Create .env.production file with Sentry DSN
      copy:
        dest: "{{ app_dir }}/.env.production"
        content: "N8N_SHORTLINK_SENTRY_DSN={{ sentry_dsn }}"
        mode: "0600"