name: Build health check

on: workflow_dispatch

jobs:
  build-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build test Docker image
        run: docker build --tag n8n-shortlink:test .

      - name: Run Docker container until health check
        run: |
          docker run --detach --publish 3001:3001 --name test-container n8n-shortlink:test
          timeout 20 bash -c 'until curl -s http://localhost:3001/health > /dev/null; do sleep 1; done'
