name: Go check

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      go_changed: ${{ steps.filter.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: tj-actions/changed-files@v43
        id: filter
        with:
          files: |
            **/*.go
            go.mod
            go.sum

  checks:
    needs: changes
    if: ${{ needs.changes.outputs.go_changed == 'true' }}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2

    - uses: actions/setup-go@v5.1.0
      with:
        go-version: 1.23.3

    - name: Lint
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        version: latest

    - name: Format check
      run: go fmt ./...

    - name: Static analysis
      run: go vet ./...
